-- GENERATED by backend/scripts/generate_content_seed_sql.py from app/libs/content_seed.py. Do not edit by hand.
-- Idempotent: rows that already exist are never changed, so edits made in the back office survive a re-run.
-- Evidenced items only, image_url NULL. Idempotent by title. Remove with:
--   DELETE FROM progress_timeline WHERE created_by = 'seed:content-2026-10';
--   DELETE FROM achievements WHERE created_by = 'seed:content-2026-10';

INSERT INTO progress_timeline (title, short_story, achievement_date, image_url, status, display_order,
                               is_published, created_by, created_at, updated_at)
SELECT v.title, v.story, v.d::date, NULL, v.status, v.ord, v.pub, 'seed:content-2026-10', now(), now()
FROM (VALUES
  ('Central Bank of Lesotho notified of the licence application lead', 'The Central Bank of Lesotho was notified that Citizen Digital has been appointed to lead the licence application. This is a notification, not an approval: no licence has been granted.', '2026-08-01', 'completed', 10, FALSE),
  ('First Quarterly Review published', 'Citizen Digital published its first Quarterly Review, which replaces the newsletter series.', '2026-08-01', 'completed', 20, FALSE),
  ('Member verification and RSVP system built', 'A system to verify members and record RSVPs for general meetings was built.', '2026-08-16', 'completed', 30, TRUE),
  ('Board and Shareholders Meeting held', 'A combined Board and Shareholders Meeting was held on 17 August 2026.', '2026-08-17', 'completed', 40, TRUE),
  ('Company records moved into a structured library', 'The company''s records were moved into a structured records library.', '2026-08-30', 'completed', 50, TRUE),
  ('Licence application not yet lodged', 'The target of 1 September 2026 for lodging the licence application with the Central Bank of Lesotho was not met. The application has not yet been lodged.', '2026-09-01', 'in_progress', 60, FALSE),
  ('Banking platform build begins', 'Work starts on the technology behind Citizen Bank: a core ledger, internet banking for the web and a mobile banking app. A working prototype was built using demonstration data only.', '2026-09-25', 'completed', 70, TRUE),
  ('Citizen AI assistant added', 'Our AI assistant can answer questions about a customer''s own accounts and prepare payments for the customer to confirm. It cannot move money by itself.', '2026-09-25', 'completed', 80, TRUE),
  ('Investor and board platform prepared for launch', 'The investor, share subscription and board tools are consolidated into one codebase with production launch settings.', '2026-09-27', 'completed', 90, TRUE),
  ('Licence submission pack prepared', 'A 44-document submission pack for the Central Bank of Lesotho licence application was prepared. It has not been lodged and is not an approval.', '2026-09-27', 'completed', 100, TRUE),
  ('Business plan revised', 'Version 1.1 of the business plan was issued as part of the licence submission pack.', '2026-09-28', 'completed', 110, TRUE),
  ('Passkey sign-in and step-by-step identity checks', 'Customers can sign in with a passkey, and identity checks are requested only when a product needs them. This is a demonstration policy; no external verification providers are connected yet.', '2026-10-05', 'completed', 120, TRUE),
  ('Spoken AI replies, clearly labelled as AI', 'Citizen AI can speak its replies in the web and mobile apps, and tells the customer that the voice is AI-generated.', '2026-10-05', 'completed', 130, TRUE),
  ('Backup AI provider for reliability', 'If the main AI service is unavailable, a second provider takes over so the assistant keeps working.', '2026-10-05', 'completed', 140, TRUE),
  ('One Citizen sign-in across website, Hub and banking', 'A person signs in once on the website and is passed securely to internet banking or the mobile app without a second login.', '2026-10-06', 'completed', 150, TRUE),
  ('Shared identity design for the whole platform', 'One person record and one set of roles now sit behind the website, Hub and banking.', '2026-10-06', 'completed', 160, TRUE),
  ('Website rebuilt to run on a modern hosting stack', 'The website and its API no longer depend on the original site-builder platform. The live site itself is still being moved.', '2026-10-06', 'completed', 170, TRUE),
  ('Demonstration environment opened', 'A separate demonstration of the platform with seven role accounts, with automated checks of what each role can reach. All banking in it is simulated.', '2026-10-06', 'completed', 180, TRUE),
  ('Automated testing on every repository', 'Every code repository now runs its tests, type checks and build on each change.', '2026-10-06', 'completed', 190, TRUE),
  ('Citizen Hub becomes its own site', 'The tools for investors, shareholders, board members and staff get their own home, with role-based access.', '2026-10-06', 'completed', 200, TRUE),
  ('Citizen Hub rebuilt around 14 features', 'The Hub is being rebuilt from about 50 screens to 14 focused features, with shared error handling and screen-by-screen tests.', '2026-10-07', 'in_progress', 210, TRUE),
  ('One notification system for investors and board', 'Subscription, payment, certificate and invitation messages are moving to one notification pipeline.', '2026-10-07', 'in_progress', 220, TRUE)
) AS v(title, story, d, status, ord, pub)
WHERE NOT EXISTS (SELECT 1 FROM progress_timeline t WHERE t.title = v.title);

INSERT INTO achievements (title, description, achievement_date, category, image_url, display_order,
                          is_published, created_by, created_at, updated_at)
SELECT v.title, v.descr, v.d::date, v.category, NULL, v.ord, v.pub, 'seed:content-2026-10', now(), now()
FROM (VALUES
  ('Governance documentation drafted', 'In September 2026, draft charters for the Audit, Risk Management, Credit, and Governance and Nominations committees were prepared, with a draft shareholders'' agreement and core policies.', '2026-09-01', 'milestone', 10, FALSE),
  ('Core ledger built', 'A double-entry ledger records every transaction as balanced entries and makes payment retries safe. It runs as a simulated ledger for demonstration.', '2026-09-25', 'milestone', 20, TRUE),
  ('Internet banking and mobile app built', 'A web banking experience and an installable mobile app, both connected to the core ledger and shown as a pre-licensing demonstration.', '2026-09-25', 'milestone', 30, TRUE),
  ('Investor and board platform', 'Tools for share subscriptions, payment proof, share certificates, a data room, board meetings, votes and board document compliance.', '2026-09-27', 'milestone', 40, TRUE),
  ('Licence submission pack prepared', 'A 44-document pack for the Central Bank of Lesotho licence application was prepared. It has not been lodged and is not an approval.', '2026-09-27', 'milestone', 50, TRUE),
  ('Citizen AI with spoken replies', 'An AI assistant that answers account questions in text or voice, says that spoken replies are AI-generated, and falls back to a second provider if needed.', '2026-10-05', 'milestone', 60, TRUE),
  ('Passkey sign-in and progressive identity checks', 'Passwordless sign-in and identity checks that only appear when needed, with an audit trail and manual review. A demonstration policy with no external providers.', '2026-10-05', 'milestone', 70, TRUE),
  ('Single sign-on across website, Hub and banking', 'One identity and one login across the public site, the investor and board Hub, and both banking apps.', '2026-10-06', 'milestone', 80, TRUE),
  ('Demonstration environment verified across all roles', 'A full demonstration with seven role accounts, checked automatically against the deployed demonstration.', '2026-10-06', 'milestone', 90, TRUE)
) AS v(title, descr, d, category, ord, pub)
WHERE NOT EXISTS (SELECT 1 FROM achievements a WHERE a.title = v.title);
