"""Render the seed data in content_seed.py as idempotent SQL (used by scripts/generate_content_seed_sql.py)."""
from __future__ import annotations

import json
from pathlib import Path

from app.libs import content_seed as seed

MIGRATIONS_DIR = Path(__file__).resolve().parents[2] / "migrations" / "content"


def q(value) -> str:
    if value is None:
        return "NULL"
    if isinstance(value, bool):
        return "TRUE" if value else "FALSE"
    if isinstance(value, int):
        return str(value)
    return "'" + str(value).replace("'", "''") + "'"


def qj(value) -> str:
    return q(json.dumps(value, ensure_ascii=False)) + "::jsonb"


HEADER = (
    "-- GENERATED by backend/scripts/generate_content_seed_sql.py from app/libs/content_seed.py. Do not edit by hand.\n"
    "-- Idempotent: rows that already exist are never changed, so edits made in the back office survive a re-run.\n"
)


def newsletters_sql() -> str:
    rows = []
    for n in seed.NEWSLETTERS:
        rows.append(
            "  ({slug}, {issue}, {series}, {title}, {on}::date, {period}, {summary}, {sections}, {vis}, {status}, "
            "{sort}, {actor})".format(
                slug=q(n["slug"]), issue=q(n["issue_no"]), series=q(n["series"]), title=q(n["title"]),
                on=q(n["published_on"]), period=q(n["period_label"]), summary=q(n["summary"]),
                sections=qj(n["sections"]), vis=q(n["visibility"]), status=q(n["status"]), sort=q(n["sort_order"]),
                actor=q(seed.SEED_ACTOR)))
    return (
        HEADER + "-- Metadata only: no files, no confidential text. Nothing is seeded as public.\n"
        "INSERT INTO newsletters (slug, issue_no, series, title, published_on, period_label, summary, sections,\n"
        "                         visibility, status, sort_order, created_by)\nVALUES\n" + ",\n".join(rows) + "\n"
        "ON CONFLICT (slug) DO NOTHING;\n")


def job_adverts_sql() -> str:
    rows = []
    for a in seed.JOB_ADVERTS:
        rows.append(
            "  ({slug}, {title}, {dept}, {etype}, {loc}, {summary}, {resp}, {req}, NULL, NULL, 'draft', FALSE, "
            "{note}, {actor})".format(
                slug=q(a["slug"]), title=q(a["title"]), dept=q(a["department"]), etype=q(a["employment_type"]),
                loc=q(a["location"]), summary=q(a["summary"]), resp=qj(a["responsibilities"]),
                req=qj(a["requirements"]), note=q(a["source_note"]), actor=q(seed.SEED_ACTOR)))
    return (
        HEADER + "-- All adverts are drafts with wording_confirmed = false. No salaries. No live closing dates.\n"
        "INSERT INTO job_adverts (slug, title, department, employment_type, location, summary, responsibilities,\n"
        "                         requirements, how_to_apply, closing_date, status, wording_confirmed, source_note,\n"
        "                         created_by)\nVALUES\n" + ",\n".join(rows) + "\n"
        "ON CONFLICT (slug) DO NOTHING;\n")


def timeline_achievements_sql() -> str:
    t_rows = []
    for order, t in seed.ordered(seed.TIMELINE):
        t_rows.append("  ({title}, {story}, {d}, {status}, {order}, {pub})".format(
            title=q(t["title"]), story=q(t["story"]), d=q(t["date"]), status=q(t["status"]), order=order,
            pub=q(t["published"])))
    a_rows = []
    for order, a in seed.ordered(seed.ACHIEVEMENTS):
        a_rows.append("  ({title}, {desc}, {d}, {cat}, {order}, {pub})".format(
            title=q(a["title"]), desc=q(a["description"]), d=q(a["date"]), cat=q(a["category"]), order=order,
            pub=q(a["published"])))
    actor = q(seed.SEED_ACTOR)
    return (
        HEADER + "-- Evidenced items only, image_url NULL. Idempotent by title. Remove with:\n"
        f"--   DELETE FROM progress_timeline WHERE created_by = {actor};\n"
        f"--   DELETE FROM achievements WHERE created_by = {actor};\n\n"
        "INSERT INTO progress_timeline (title, short_story, achievement_date, image_url, status, display_order,\n"
        "                               is_published, created_by, created_at, updated_at)\n"
        f"SELECT v.title, v.story, v.d::date, NULL, v.status, v.ord, v.pub, {actor}, now(), now()\nFROM (VALUES\n"
        + ",\n".join(t_rows) + "\n) AS v(title, story, d, status, ord, pub)\n"
        "WHERE NOT EXISTS (SELECT 1 FROM progress_timeline t WHERE t.title = v.title);\n\n"
        "INSERT INTO achievements (title, description, achievement_date, category, image_url, display_order,\n"
        "                          is_published, created_by, created_at, updated_at)\n"
        f"SELECT v.title, v.descr, v.d::date, v.category, NULL, v.ord, v.pub, {actor}, now(), now()\nFROM (VALUES\n"
        + ",\n".join(a_rows) + "\n) AS v(title, descr, d, category, ord, pub)\n"
        "WHERE NOT EXISTS (SELECT 1 FROM achievements a WHERE a.title = v.title);\n")


GENERATED = {
    "004_seed_newsletters.sql": newsletters_sql,
    "005_seed_job_adverts.sql": job_adverts_sql,
    "006_seed_timeline_achievements.sql": timeline_achievements_sql,
}
