-- Reference lists (option lists for forms): one row per option. Safe to run more than once.
-- RENDERED from backend/app/libs/policy_seed.py. Rows an administrator has changed are never overwritten.
CREATE TABLE IF NOT EXISTS reference_list_items (
    list_key      text    NOT NULL,
    code          text    NOT NULL,
    label         text    NOT NULL,
    display_order integer NOT NULL DEFAULT 0,
    active        boolean NOT NULL DEFAULT true,
    meta          jsonb   NOT NULL DEFAULT '{}'::jsonb,
    PRIMARY KEY (list_key, code)
);

INSERT INTO reference_list_items (list_key, code, label, display_order, active, meta) VALUES
  ('gender', 'male', 'Male', 1, true, '{}'::jsonb),
  ('gender', 'female', 'Female', 2, true, '{}'::jsonb),
  ('gender', 'other', 'Other', 3, true, '{}'::jsonb),
  ('investor_type', 'individual', 'Individual', 1, true, '{}'::jsonb),
  ('investor_type', 'institutional', 'Institution', 2, true, '{}'::jsonb),
  ('investor_type', 'accredited', 'Accredited investor', 3, true, '{}'::jsonb),
  ('account_type', 'personal', 'Personal', 1, true, '{}'::jsonb),
  ('account_type', 'business', 'Business', 2, true, '{}'::jsonb),
  ('lead_status', 'new', 'New', 1, true, '{}'::jsonb),
  ('lead_status', 'contacted', 'Contacted', 2, true, '{}'::jsonb),
  ('lead_status', 'interested', 'Interested', 3, true, '{}'::jsonb),
  ('lead_status', 'invited', 'Invited', 4, true, '{}'::jsonb),
  ('lead_status', 'converted', 'Converted', 5, true, '{}'::jsonb),
  ('lead_status', 'declined', 'Declined', 6, true, '{}'::jsonb),
  ('lead_source', 'website', 'Website', 1, true, '{}'::jsonb),
  ('lead_source', 'referral', 'Referral', 2, true, '{}'::jsonb),
  ('lead_source', 'event', 'Event', 3, true, '{}'::jsonb),
  ('lead_source', 'social_media', 'Social media', 4, true, '{}'::jsonb),
  ('lead_source', 'direct', 'Direct', 5, true, '{}'::jsonb),
  ('meeting_type', 'regular', 'Regular', 1, true, '{}'::jsonb),
  ('meeting_type', 'special', 'Special', 2, true, '{}'::jsonb),
  ('meeting_type', 'emergency', 'Emergency', 3, true, '{}'::jsonb),
  ('meeting_type', 'agm', 'Annual general meeting', 4, true, '{}'::jsonb),
  ('meeting_type', 'egm', 'Extraordinary general meeting', 5, true, '{}'::jsonb),
  ('member_status', 'active', 'Active', 1, true, '{}'::jsonb),
  ('member_status', 'inactive', 'Inactive', 2, true, '{}'::jsonb),
  ('member_status', 'resigned', 'Resigned', 3, true, '{}'::jsonb),
  ('member_status', 'removed', 'Removed', 4, true, '{}'::jsonb),
  ('jurisdiction', 'global', 'Global', 1, true, '{}'::jsonb),
  ('jurisdiction', 'lesotho', 'Lesotho', 2, true, '{}'::jsonb),
  ('jurisdiction', 'south_africa', 'South Africa', 3, true, '{}'::jsonb),
  ('jurisdiction', 'botswana', 'Botswana', 4, true, '{}'::jsonb),
  ('crypto_asset', 'BTC', 'Bitcoin', 1, true, '{"hint": "A Bitcoin address starts with bc1, 1 or 3", "regex": "^(bc1[02-9ac-hj-np-z]{11,71}|[13][1-9A-HJ-NP-Za-km-z]{25,34})$"}'::jsonb),
  ('crypto_asset', 'ETH', 'Ethereum', 2, true, '{"hint": "An Ethereum address is 0x followed by 40 hex characters", "regex": "^0x[0-9a-fA-F]{40}$"}'::jsonb),
  ('crypto_asset', 'USDT', 'Tether (USDT)', 3, true, '{"hint": "A USDT address is 0x… (Ethereum network) or T… (Tron network)", "regex": "^(0x[0-9a-fA-F]{40}|T[1-9A-HJ-NP-Za-km-z]{33})$"}'::jsonb),
  ('certificate_signer_role', 'company_secretary', 'Company secretary', 1, true, '{}'::jsonb),
  ('certificate_signer_role', 'chairman', 'Chairman', 2, true, '{}'::jsonb),
  ('certificate_signer_role', 'director', 'Director', 3, true, '{}'::jsonb),
  ('certificate_signer_role', 'authorized_official', 'Authorised official', 4, true, '{}'::jsonb),
  ('document_type', 'minutes', 'Minutes', 1, true, '{}'::jsonb),
  ('document_type', 'agenda', 'Agenda', 2, true, '{}'::jsonb),
  ('document_type', 'resolution_attachment', 'Resolution attachment', 3, true, '{}'::jsonb),
  ('document_type', 'supporting_doc', 'Supporting document', 4, true, '{}'::jsonb),
  ('document_type', 'presentation', 'Presentation', 5, true, '{}'::jsonb)
ON CONFLICT (list_key, code) DO NOTHING;
