import {notFound,redirect} from 'next/navigation';

import {serviceRoutes,serviceURL} from '@/lib/services';
const pages:Record<string,{title:string;kicker:string;body:string[]}>={
 about:{title:'A future built around citizens.',kicker:'OUR STORY',body:['Citizen Bank brings customers, investors and institutional leadership into a connected ecosystem. Our focus is a simpler experience, clear responsibilities and a shared Citizen identity.','We are preparing for licensing. Customer banking remains a demonstration while the institutional workspace supports investment participation and governance.']},
 services:{title:'Banking that fits your life.',kicker:'CUSTOMER SERVICES',body:['Explore Internet Banking or the Citizen Banking App. Customer account opening and profile maintenance take place in the banking systems.','Banking is currently available for demonstration. Real deposits and banking transactions are not available at the pre-licensing stage.']},
 contact:{title:'Connect with Citizen.',kicker:'CONTACT',body:['Existing investors, shareholders and board members can access their institutional records and updates in Citizen Hub. Customers can manage their banking profile in Internet Banking or the Citizen App.','Public contact details are being finalised. Additional support channels are coming soon.']},
 privacy:{title:'Your information. Your trust.',kicker:'PRIVACY',body:['Profiles and permissions are maintained within the service you use. Citizen Hub manages institutional information; banking systems manage customer activities. Documents are referenced through Google Drive shared links.','The complete privacy notice is being finalised before market launch. Use fictional information when exploring demonstration accounts.']},
 terms:{title:'Where we are today.',kicker:'TERMS & AVAILABILITY',body:['Citizen Bank is in the pre-licensing stage. Demonstration banking accounts contain fictional records and do not move real money.','Participation as an investor or shareholder is managed through Citizen Hub and its applicable agreements. Do not treat a demonstration balance or allocation as a real investment. Complete service terms are being finalised before market launch.']}
};
export default async function Page({params}:{params:Promise<{slug:string[]}>}){const{slug}=await params;const key=slug.join('/');const route=serviceRoutes[key];if(route)redirect(serviceURL(route.service,route.path));const page=pages[key];if(!page)notFound();return <section className="information section"><span className="eyebrow">{page.kicker}</span><h1>{page.title}</h1>{page.body.map(text=><p key={text}>{text}</p>)}<div className="actions"><a className="button primary" href={key==='services'?'/internet-banking':'/hub'}>{key==='services'?'Explore Internet Banking':'Open Citizen Hub'} ↗</a><a className="button quiet" href="/">Back to website</a></div>{key==='services'&&<a className="app-link" href="/mobile-banking">Explore the Citizen Banking App →</a>}</section>;}
