
// THIS FILE IS AUTOGENERATED WHEN PAGES ARE UPDATED
import { RouteObject } from "react-router-dom";


import { UserGuard } from "./app/auth";



import { StackHandlerRoutes, LoginRedirect } from "./app/auth";


import App from "./pages/App.tsx";
import BranchLocator from "./pages/BranchLocator.tsx";
import Contact from "./pages/Contact.tsx";
import CookiePolicy from "./pages/CookiePolicy.tsx";
import DemoLauncher from "./pages/DemoLauncher.tsx";
import DevSetup from "./pages/DevSetup.tsx";
import Disclosures from "./pages/Disclosures.tsx";
import Faqs from "./pages/Faqs.tsx";
import ForbiddenPage from "./pages/ForbiddenPage.tsx";
import ForeignExchange from "./pages/ForeignExchange.tsx";
import HelpCenter from "./pages/HelpCenter.tsx";
import Invite from "./pages/Invite.tsx";
import InviteAcceptance from "./pages/InviteAcceptance.tsx";
import Media from "./pages/Media.tsx";
import NoRoles from "./pages/NoRoles.tsx";
import NotificationAnalytics from "./pages/NotificationAnalytics.tsx";
import Offline from "./pages/Offline.tsx";
import PrivacyPolicy from "./pages/PrivacyPolicy.tsx";
import SecurityTips from "./pages/SecurityTips.tsx";
import Support from "./pages/Support.tsx";
import Sustainability from "./pages/Sustainability.tsx";
import TermsOfService from "./pages/TermsOfService.tsx";
import UnauthorizedPage from "./pages/UnauthorizedPage.tsx";
import VerifyCertificate from "./pages/VerifyCertificate.tsx";

import ServiceRedirect from "./components/ServiceRedirect";
import { MOVED_TO_HUB } from "./utils/hub";

export const userRoutes: RouteObject[] = [
  ...MOVED_TO_HUB.map(path => ({ path, element: <ServiceRedirect /> })),
  { path: "/board-meetings/*", element: <ServiceRedirect /> },
  ...["/auth/sign-in", "/auth/sign-up", "/demo", "/demo/launch", "/customer-portal", "/customerportal", "/open-account", "/mobile-banking", "/profile", "/complete-profile", "/completeprofile", "/notification-preferences", "/notificationpreferences"].map(path => ({path, element:<ServiceRedirect />})),

	{ path: "/auth/redirect", element: <LoginRedirect /> },
	{ path: "/auth/*", element: <StackHandlerRoutes /> },
	{ path: "/admin-audit", element: <ServiceRedirect /> },
	{ path: "/adminaudit", element: <ServiceRedirect /> },
	{ path: "/admin-board-positions", element: <ServiceRedirect /> },
	{ path: "/adminboardpositions", element: <ServiceRedirect /> },
	{ path: "/admin-dashboard", element: <ServiceRedirect /> },
	{ path: "/admindashboard", element: <ServiceRedirect /> },
	{ path: "/admin-setup-guide", element: <ServiceRedirect /> },
	{ path: "/adminsetupguide", element: <ServiceRedirect /> },
	{ path: "/admin-user-detail", element: <ServiceRedirect /> },
	{ path: "/adminuserdetail", element: <ServiceRedirect /> },
	{ path: "/admin-users", element: <ServiceRedirect /> },
	{ path: "/adminusers", element: <ServiceRedirect /> },
	{ path: "/", element: <App /> },
	{ path: "/back-office-achievements", element: <ServiceRedirect /> },
	{ path: "/backofficeachievements", element: <ServiceRedirect /> },
	{ path: "/back-office-admin-subscriptions", element: <ServiceRedirect /> },
	{ path: "/backofficeadminsubscriptions", element: <ServiceRedirect /> },
	{ path: "/back-office-bank-accounts", element: <ServiceRedirect /> },
	{ path: "/backofficebankaccounts", element: <ServiceRedirect /> },
	{ path: "/back-office-board-documents", element: <ServiceRedirect /> },
	{ path: "/backofficeboarddocuments", element: <ServiceRedirect /> },
	{ path: "/back-office-board-investments", element: <ServiceRedirect /> },
	{ path: "/backofficeboardinvestments", element: <ServiceRedirect /> },
	{ path: "/back-office-board-mapping", element: <ServiceRedirect /> },
	{ path: "/backofficeboardmapping", element: <ServiceRedirect /> },
	{ path: "/back-office-board-members", element: <ServiceRedirect /> },
	{ path: "/backofficeboardmembers", element: <ServiceRedirect /> },
	{ path: "/back-office-certificate-templates", element: <ServiceRedirect /> },
	{ path: "/backofficecertificatetemplates", element: <ServiceRedirect /> },
	{ path: "/back-office-certificates", element: <ServiceRedirect /> },
	{ path: "/backofficecertificates", element: <ServiceRedirect /> },
	{ path: "/back-office-crypto-wallets", element: <ServiceRedirect /> },
	{ path: "/backofficecryptowallets", element: <ServiceRedirect /> },
	{ path: "/back-office-dashboard", element: <ServiceRedirect /> },
	{ path: "/backofficedashboard", element: <ServiceRedirect /> },
	{ path: "/back-office-data-room", element: <ServiceRedirect /> },
	{ path: "/backofficedataroom", element: <ServiceRedirect /> },
	{ path: "/back-office-data-room-access", element: <ServiceRedirect /> },
	{ path: "/backofficedataroomaccess", element: <ServiceRedirect /> },
	{ path: "/back-office-engagement", element: <ServiceRedirect /> },
	{ path: "/backofficeengagement", element: <ServiceRedirect /> },
	{ path: "/back-office-investor-leads", element: <ServiceRedirect /> },
	{ path: "/backofficeinvestorleads", element: <ServiceRedirect /> },
	{ path: "/back-office-invitations", element: <ServiceRedirect /> },
	{ path: "/backofficeinvitations", element: <ServiceRedirect /> },
	{ path: "/back-office-license-documents", element: <ServiceRedirect /> },
	{ path: "/backofficelicensedocuments", element: <ServiceRedirect /> },
	{ path: "/back-office-media-releases", element: <ServiceRedirect /> },
	{ path: "/backofficemediareleases", element: <ServiceRedirect /> },
	{ path: "/back-office-sent-items", element: <ServiceRedirect /> },
	{ path: "/backofficesentitems", element: <ServiceRedirect /> },
	{ path: "/back-office-share-classes", element: <ServiceRedirect /> },
	{ path: "/backofficeshareclasses", element: <ServiceRedirect /> },
	{ path: "/back-office-subscribe-on-behalf", element: <ServiceRedirect /> },
	{ path: "/backofficesubscribeonbehalf", element: <ServiceRedirect /> },
	{ path: "/back-office-subscriptions", element: <ServiceRedirect /> },
	{ path: "/backofficesubscriptions", element: <ServiceRedirect /> },
	{ path: "/board-documents", element: <ServiceRedirect /> },
	{ path: "/boarddocuments", element: <ServiceRedirect /> },
	{ path: "/board-investment", element: <ServiceRedirect /> },
	{ path: "/boardinvestment", element: <ServiceRedirect /> },
	{ path: "/board-meetings", element: <ServiceRedirect /> },
	{ path: "/boardmeetings", element: <ServiceRedirect /> },
	{ path: "/board-member-detail", element: <ServiceRedirect /> },
	{ path: "/boardmemberdetail", element: <ServiceRedirect /> },
	{ path: "/board-onboarding", element: <ServiceRedirect /> },
	{ path: "/boardonboarding", element: <ServiceRedirect /> },
	{ path: "/board-portal", element: <ServiceRedirect /> },
	{ path: "/boardportal", element: <ServiceRedirect /> },
	{ path: "/board-portal-invitations", element: <ServiceRedirect /> },
	{ path: "/boardportalinvitations", element: <ServiceRedirect /> },
	{ path: "/branch-locator", element: <BranchLocator /> },
	{ path: "/branchlocator", element: <BranchLocator /> },
	{ path: "/communication-portal", element: <ServiceRedirect /> },
	{ path: "/communicationportal", element: <ServiceRedirect /> },
	{ path: "/complete-profile", element: <ServiceRedirect /> },
	{ path: "/completeprofile", element: <ServiceRedirect /> },
	{ path: "/contact", element: <Contact /> },
	{ path: "/cookie-policy", element: <CookiePolicy /> },
	{ path: "/cookiepolicy", element: <CookiePolicy /> },
	{ path: "/create-meeting", element: <ServiceRedirect /> },
	{ path: "/createmeeting", element: <ServiceRedirect /> },
	{ path: "/customer-portal", element: <ServiceRedirect /> },
	{ path: "/demo", element: <ServiceRedirect /> },
	{ path: "/demo/launch", element: <UserGuard><DemoLauncher /></UserGuard> },
	{ path: "/customerportal", element: <ServiceRedirect /> },
	{ path: "/data-room", element: <ServiceRedirect /> },
	{ path: "/dataroom", element: <ServiceRedirect /> },
	{ path: "/data-room-access", element: <ServiceRedirect /> },
	{ path: "/dataroomaccess", element: <ServiceRedirect /> },
	{ path: "/dev-setup", element: <UserGuard><DevSetup /></UserGuard> },
	{ path: "/devsetup", element: <UserGuard><DevSetup /></UserGuard> },
	{ path: "/disclosures", element: <Disclosures /> },
	{ path: "/faqs", element: <Faqs /> },
	{ path: "/forbidden-page", element: <ForbiddenPage /> },
	{ path: "/forbiddenpage", element: <ForbiddenPage /> },
	{ path: "/foreign-exchange", element: <ForeignExchange /> },
	{ path: "/foreignexchange", element: <ForeignExchange /> },
	{ path: "/governance", element: <ServiceRedirect /> },
	{ path: "/governance-admin", element: <ServiceRedirect /> },
	{ path: "/governanceadmin", element: <ServiceRedirect /> },
	{ path: "/help-center", element: <HelpCenter /> },
	{ path: "/helpcenter", element: <HelpCenter /> },
	{ path: "/invest", element: <ServiceRedirect /> },
	{ path: "/invite", element: <Invite /> },
	{ path: "/invite-acceptance", element: <InviteAcceptance /> },
	{ path: "/inviteacceptance", element: <InviteAcceptance /> },
	{ path: "/media", element: <Media /> },
	{ path: "/meeting-details", element: <ServiceRedirect /> },
	{ path: "/meetingdetails", element: <ServiceRedirect /> },
	{ path: "/my-agreements", element: <ServiceRedirect /> },
	{ path: "/myagreements", element: <ServiceRedirect /> },
	{ path: "/my-subscriptions", element: <ServiceRedirect /> },
	{ path: "/mysubscriptions", element: <ServiceRedirect /> },
	{ path: "/no-roles", element: <NoRoles /> },
	{ path: "/noroles", element: <NoRoles /> },
	{ path: "/notification-analytics", element: <NotificationAnalytics /> },
	{ path: "/notificationanalytics", element: <NotificationAnalytics /> },
	{ path: "/notification-preferences", element: <ServiceRedirect /> },
	{ path: "/notificationpreferences", element: <ServiceRedirect /> },
	{ path: "/offline", element: <Offline /> },
	{ path: "/privacy-policy", element: <PrivacyPolicy /> },
	{ path: "/privacypolicy", element: <PrivacyPolicy /> },
	{ path: "/profile", element: <ServiceRedirect /> },
	{ path: "/security-tips", element: <SecurityTips /> },
	{ path: "/securitytips", element: <SecurityTips /> },
	{ path: "/share-subscription", element: <ServiceRedirect /> },
	{ path: "/sharesubscription", element: <ServiceRedirect /> },
	{ path: "/sign-certificate", element: <ServiceRedirect /> },
	{ path: "/signcertificate", element: <ServiceRedirect /> },
	{ path: "/support", element: <Support /> },
	{ path: "/sustainability", element: <Sustainability /> },
	{ path: "/terms-of-service", element: <TermsOfService /> },
	{ path: "/termsofservice", element: <TermsOfService /> },
	{ path: "/unauthorized-page", element: <UnauthorizedPage /> },
	{ path: "/unauthorizedpage", element: <UnauthorizedPage /> },
	{ path: "/verify-certificate", element: <VerifyCertificate /> },
	{ path: "/verifycertificate", element: <VerifyCertificate /> },

];
